name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Add EC2 Host Key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
    - name: Test SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh -v -i ~/.ssh/id_rsa ubuntu@"${{ secrets.EC2_HOST }}" "echo Connected!"
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          fuser -k 5000/tcp
          cd ~/${{ github.event.repository.name }}
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python app.py > app.log 2>&1 &
